/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class shiqichan_singinapp_PersonDetector */

#ifndef _Included_shiqichan_singinapp_PersonDetector
#define _Included_shiqichan_singinapp_PersonDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     shiqichan_singinapp_PersonDetector
 * Method:    detect
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_shiqichan_singinapp_PersonDetector_detect
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
